=== Metron-Project/metroninfo/drafts/v0.1/MetronInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="MetronInfo" type="metroninfoType" />
    <!-- Complex Types -->
    <xs:complexType name="metroninfoType">
        <xs:sequence>
            <xs:element name="ID" type="sourceType" minOccurs="0" />
            <xs:element name="Publisher" type="xs:string" />
            <xs:element name="Series" type="seriesType" />
            <xs:element name="Volume" type="xs:int" minOccurs="0" />
            <xs:element name="Number" type="xs:string" /> <!-- Should there always be a number? -->
            <xs:element name="Stories" type="storyType" minOccurs="0" /> <!-- Story titles in issue -->
            <xs:element name="Summary" type="xs:string" minOccurs="0" />
            <xs:element name="Price" type="priceType" minOccurs="0" />
            <xs:element name="CoverDate" type="xs:date" />
            <xs:element name="StoreDate" type="xs:date" minOccurs="0" />
            <xs:element name="PageCount" type="xs:int" default="0" />
            <xs:element name="Genres" type="genresType" minOccurs="0" />
            <xs:element name="Tags" type="tagsType" minOccurs="0" />
            <xs:element name="Arcs" type="arcsType" minOccurs="0" />
            <xs:element name="Characters" type="charactersType" minOccurs="0" />
            <xs:element name="Teams" type="teamsType" minOccurs="0" />
            <xs:element name="Locations" type="locationsType" minOccurs="0" />
            <xs:element name="GTIN" type="gtinType" minOccurs="0" maxOccurs="2"/>
            <xs:element name="BlackAndWhite" type="xs:boolean" minOccurs="0" default="false" />
            <xs:element name="AgeRating" type="ratingType" minOccurs="0" default="Unknown" />
            <xs:element name="URL" type="xs:string" minOccurs="0" /> <!-- Should we make this an array? -->
            <xs:element name="Credits" type="creditsType" minOccurs="0" />
            <xs:element name="Pages" type="ArrayOfComicPageInfo" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="seriesType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="SortName" type="xs:string" />
            <xs:element name="Type" type="publicationType" />
        </xs:sequence>
        <xs:attribute name="lang" type="xs:string" default="EN" />
    </xs:complexType>
    <xs:complexType name="sourceType">
        <xs:simpleContent>
            <xs:extension base="xs:int">
                <xs:attribute name="source" type="informationSource" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="arcsType">
        <xs:sequence>
            <xs:element name="Arc" type="arcType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="arcType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="Number" type="xs:int" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="charactersType">
        <xs:sequence>
            <xs:element name="Character" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="genresType">
        <xs:sequence>
            <xs:element name="Genre" type="genreType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="Story" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="Tag" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="teamsType">
        <xs:sequence>
            <xs:element name="Team" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="locationsType">
        <xs:sequence>
            <xs:element name="Location" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="creditsType">
        <xs:sequence>
            <xs:element name="Credit" type="creditType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="rolesType">
        <xs:sequence>
            <xs:element name="Role" type="roleType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="creditType">
        <xs:sequence>
            <xs:element name="Creator" type="xs:string" />
            <xs:element name="Roles" type="rolesType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="priceType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="currency" type="currencyType" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <!-- TODO: Probably need to add some restrictions on lenth.-->
    <xs:complexType name="gtinType">
        <xs:simpleContent>
            <xs:extension base="xs:long">
                <xs:attribute name="structure" type="gtinStructureType" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ArrayOfComicPageInfo">
        <xs:sequence>
            <xs:element name="Page" type="ComicPageInfo" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ComicPageInfo">
        <xs:attribute name="Image" type="xs:int" use="required" />
        <xs:attribute name="Type" type="ComicPageType" default="Story" />
        <xs:attribute name="DoublePage" type="xs:boolean" default="false" />
        <xs:attribute name="ImageSize" type="xs:long" default="0" />
        <xs:attribute name="Key" type="xs:string" default="" />
        <xs:attribute name="Bookmark" type="xs:string" default="" />
        <xs:attribute name="ImageWidth" type="xs:int" default="-1" />
        <xs:attribute name="ImageHeight" type="xs:int" default="-1" />
    </xs:complexType>

    <!-- Simple Types -->
    <xs:simpleType name="gtinStructureType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="isbn" />
            <xs:enumeration value="upc" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="publicationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Annual" />
            <xs:enumeration value="Graphic Novel" />
            <xs:enumeration value="Limited" /> <!-- Used for mini/maxi series -->
            <xs:enumeration value="One-Shot" />
            <xs:enumeration value="Series" /> <!-- Needs better name, but used for Ongoing/Cancelled series -->
            <xs:enumeration value="Trade Paperback" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="informationSource">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Comic Vine" />
            <xs:enumeration value="Grand Comics Database" />
            <xs:enumeration value="Metron" />
            <xs:enumeration value="League of Comic Geeks" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="roleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Writer" />
            <xs:enumeration value="Penciller" />
            <xs:enumeration value="Inker" />
            <xs:enumeration value="Colorist" />
            <xs:enumeration value="Letterer" />
            <xs:enumeration value="Cover" />
            <xs:enumeration value="Assistant Editor" />
            <xs:enumeration value="Associate Editor" />
            <xs:enumeration value="Editor" />
            <xs:enumeration value="Group Editor" />
            <xs:enumeration value="Editor in Chief" />
            <xs:enumeration value="Publisher" />
            <xs:enumeration value="Translator" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="genreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Adult" />
            <xs:enumeration value="Crime" />
            <xs:enumeration value="Espionage" />
            <xs:enumeration value="Fantasy" />
            <xs:enumeration value="Historical" />
            <xs:enumeration value="Horror" />
            <xs:enumeration value="Humor" />
            <xs:enumeration value="Manga" />
            <xs:enumeration value="Parody" />
            <xs:enumeration value="Romance" />
            <xs:enumeration value="Science Fiction" />
            <xs:enumeration value="Sport" />
            <xs:enumeration value="Super-Hero" />
            <xs:enumeration value="War" />
            <xs:enumeration value="Western" />
        </xs:restriction>
    </xs:simpleType>
    <!-- Don't really care for age ratings values used by ComicInfo, but for now let's use it. -->
    <xs:simpleType name="ratingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Unknown" />
            <xs:enumeration value="Adults Only 18+" />
            <xs:enumeration value="Early Childhood" />
            <xs:enumeration value="Everyone" />
            <xs:enumeration value="Everyone 10+" />
            <xs:enumeration value="G" />
            <xs:enumeration value="Kids to Adults" />
            <xs:enumeration value="M" />
            <xs:enumeration value="MA15+" />
            <xs:enumeration value="Mature 17+" />
            <xs:enumeration value="PG" />
            <xs:enumeration value="R18+" />
            <xs:enumeration value="Rating Pending" />
            <xs:enumeration value="Teen" />
            <xs:enumeration value="X18+" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pounds" />
            <xs:enumeration value="euros" />
            <xs:enumeration value="dollars" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ComicPageType">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="FrontCover" />
                    <xs:enumeration value="InnerCover" />
                    <xs:enumeration value="Roundup" />
                    <xs:enumeration value="Story" />
                    <xs:enumeration value="Advertisement" />
                    <xs:enumeration value="Editorial" />
                    <xs:enumeration value="Letters" />
                    <xs:enumeration value="Preview" />
                    <xs:enumeration value="BackCover" />
                    <xs:enumeration value="Other" />
                    <xs:enumeration value="Deleted" />
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>
</xs:schema>

=== Metron-Project/metroninfo/schema/v1.1/Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetronInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MetronInfo.xsd">
    <IDS>
        <ID source="Metron" primary="true">290431</ID>
        <ID source="Comic Vine">12345</ID>
        <ID source="Grand Comics Database">543</ID>
        <ID source="MangaDex">8b34f37a-0181-4f0b-8ce3-01217e9a602c</ID>
    </IDS>
    <Publisher id="12345">
        <Name>DC Comics</Name>
        <Imprint id="1234">Vertigo</Imprint>
    </Publisher>
    <Series id="65478" lang="en">
        <Name>Justice League</Name>
        <SortName>Justice League</SortName>
        <Volume>2</Volume>
        <Format>Single Issue</Format>
        <StartYear>1970</StartYear>
        <IssueCount>60</IssueCount>
        <VolumeCount>3</VolumeCount>
        <AlternativeNames>
            <AlternativeName id="1234">Foo</AlternativeName>
            <AlternativeName lang="de">Hüsker Dü</AlternativeName>
        </AlternativeNames>
    </Series>
    <Number>1</Number>
    <Stories>
        <Story id="12">Justice League, Part One</Story>
        <Story>Justice League, Part Two</Story>
    </Stories>
    <Summary>In a universe where superheroes are strange and new, Batman has discovered a dark evil that requires him to unite the World Greatest Heroes!</Summary>
    <Notes>Nothing really to say.</Notes>
    <Prices>
        <Price country="US">3.99</Price>
        <Price country="GB">1.51</Price>
    </Prices>
    <CoverDate>2011-10-01</CoverDate>
    <StoreDate>2011-08-31</StoreDate>
    <PageCount>32</PageCount>
    <Genres>
        <Genre id="98745">Super-Hero</Genre>
        <Genre>Crime</Genre>
        <Genre>Foo Bar</Genre>
    </Genres>
    <Tags>
        <Tag id="78945">Foo</Tag>
        <Tag>Bar</Tag>
    </Tags>
    <Arcs>
        <Arc id="78945">
            <Name>Origin</Name>
            <Number>1</Number>
        </Arc>
        <Arc>
            <Name>The New 52!</Name>
        </Arc>
    </Arcs>
    <Characters>
        <Character id="45678">Aquaman</Character>
        <Character>Batman</Character>
        <Character>Cyborg</Character>
        <Character>Deadman</Character>
        <Character>Barry Allen</Character>
        <Character>Hal Jordan</Character>
        <Character>Hawkman</Character>
        <Character>Mera</Character>
        <Character>Pandora</Character>
        <Character>Ray Palmer</Character>
        <Character>Superman</Character>
        <Character>Wonder Woman</Character>
    </Characters>
    <Teams>
        <Team id="49948">Justice League</Team>
        <Team>Parademons</Team>
    </Teams>
    <Universes>
        <Universe id="24">
            <Name>ABC</Name>
            <Designation>Earth 25</Designation>
        </Universe>
        <Universe>
            <Name>Amalgam</Name>
        </Universe>
    </Universes>
    <Locations>
        <Location id="12389">Gotham City</Location>
        <Location>Metropolis</Location>
    </Locations>
    <GTIN>
        <ISBN>1234567890123</ISBN>
        <UPC>76194130593600111</UPC>
    </GTIN>
    <AgeRating>Everyone</AgeRating>
    <CommunityRating>
        <AverageRating>4.5</AverageRating>
        <RatingCount>1250</RatingCount>
    </CommunityRating>
    <Reprints>
        <Reprint id="65498">Foo Bar #001 (2002)</Reprint>
        <Reprint>Foo Bar #002 (2022)</Reprint>
    </Reprints>
    <URLs>
        <URL primary="true">https://comicvine.gamespot.com/justice-league-1-justice-league-part-one/4000-290431/</URL>
        <URL>https://foo.bar</URL>
        <URL>https://bar.foo</URL>
    </URLs>
    <Credits>
        <Credit>
            <Creator id="32165">Geoff Johns</Creator>
            <Roles>
                <Role id="32165">Writer</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>David Finch</Creator>
            <Roles>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Richard Friend</Creator>
            <Roles>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Jim Lee</Creator>
            <Roles>
                <Role>Penciller</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Scott Williams</Creator>
            <Roles>
                <Role>Inker</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Alex Sinclair</Creator>
            <Roles>
                <Role>Colorist</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Pat Brosseau</Creator>
            <Roles>
                <Role>Letterer</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Rex Ogle</Creator>
            <Roles>
                <Role>Associate Editor</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Eddie Berganza</Creator>
            <Roles>
                <Role>Editor</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Dan DiDio</Creator>
            <Roles>
                <Role>Publisher</Role>
            </Roles>
        </Credit>
    </Credits>
    <LastModified>2023-05-31T09:00:46.300882-04:00</LastModified>
</MetronInfo>
